In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('sudoku.csv')
df.head()

quizzes  \
0  0043002090050090010700600430060020871900074000...   
1  0401000501070039605200080000000000170009068008...   
2  6001203840084590720000060050002640300700800069...   
3  4972000001004000050000160986203000403009000000...   
4  0059103080094030600275001000300002010008200070...   

                                           solutions  
0  8643712593258497619712658434361925871986574322...  
1  3461792581875239645296483719658324174729168358...  
2  6951273841384596727248369158512647392739815469...  
3  4972583161864397252537164986293815473759641828...  
4  4659123781894735623275681497386452919548216372...

In [508]:
def generate_matrix(string):
    puzzle = np.array([list(x) for x in string],dtype='int').reshape(9,9)
    return puzzle
def gen_sol_matrix(string):
    puzzle = np.array([list(x) for x in string],dtype='int').reshape(9,9)
    return puzzle

In [474]:
def get_row(arr,row_block,row):
    return list(arr[row_block,:,row].reshape(9))

def get_col(arr,col_block,col):
    return list(arr[:,:,:,col][:,col_block].reshape(9))

def get_block(arr,col,row):
    return list(arr[col*3:(col*3)+3,row*3:(row*3)+3].reshape(9))
    

def get_diagnol(arr,index):
    return flatten_matrix(arr).diagonal(index)
    
def get_diagnoals_2(arr,i,j):
    if j-i > 0:
        return arr.diagonal(j)
    elif j-1 < 0:
        return arr.diagonal(-i)
    else:
        return arr.diagonal(0)

In [475]:
def remove_similar_elements(range_list, array_to_check):
    for i in array_to_check:
        if i in range_list:
            range_list.remove(i)
    return range_list

def check_rules(fm,i,j):
    range_list = [x for x in range(1,10)]
    row_list = [x for x in fm[i] if x != 0]
    col_list = [x for x in fm[:,j] if x != 0 ]
    block_list = [x for x in get_block(fm,i//3,j//3) if x != 0]
    removed_row = remove_similar_elements(range_list,row_list)
    removed_col = remove_similar_elements(removed_row,col_list)
    removed_block = remove_similar_elements(removed_col,block_list)   
    return removed_block

In [490]:
def solve_sudoku(fm):
    for i in range(0,9):
        for j in range(0,9):
            if fm[i][j] == 0:
                predicted_ans = check_rules(fm,i,j)
                if len(predicted_ans) == 1:
                    fm[i][j] = predicted_ans[0]
    
    if 0 not in fm:
        return fm
        
    else:
        return solve_sudoku(fm)

In [510]:
%%time
# solve_sudoku(generate_matrix(df['quizzes'][0:1])[0])

ind = 1
print("quiz sudoku : \n",generate_matrix(df['quizzes'][ind]))
print("solved sudoku : \n",solve_sudoku(generate_matrix(df['quizzes'][ind])))
print("solution sodoku : \n",  gen_sol_matrix(df['solutions'][ind]))

quiz sudoku : 
 [[0 4 0 1 0 0 0 5 0]
 [1 0 7 0 0 3 9 6 0]
 [5 2 0 0 0 8 0 0 0]
 [0 0 0 0 0 0 0 1 7]
 [0 0 0 9 0 6 8 0 0]
 [8 0 3 0 5 0 6 2 0]
 [0 9 0 0 6 0 5 4 3]
 [6 0 0 0 8 0 7 0 0]
 [2 5 0 0 9 7 1 0 0]]
solved sudoku : 
 [[3 4 6 1 7 9 2 5 8]
 [1 8 7 5 2 3 9 6 4]
 [5 2 9 6 4 8 3 7 1]
 [9 6 5 8 3 2 4 1 7]
 [4 7 2 9 1 6 8 3 5]
 [8 1 3 7 5 4 6 2 9]
 [7 9 8 2 6 1 5 4 3]
 [6 3 1 4 8 5 7 9 2]
 [2 5 4 3 9 7 1 8 6]]
solution sodoku : 
 [[3 4 6 1 7 9 2 5 8]
 [1 8 7 5 2 3 9 6 4]
 [5 2 9 6 4 8 3 7 1]
 [9 6 5 8 3 2 4 1 7]
 [4 7 2 9 1 6 8 3 5]
 [8 1 3 7 5 4 6 2 9]
 [7 9 8 2 6 1 5 4 3]
 [6 3 1 4 8 5 7 9 2]
 [2 5 4 3 9 7 1 8 6]]
CPU times: user 5.87 ms, sys: 1.14 ms, total: 7.01 ms
Wall time: 5.95 ms
